# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Open Gazettes Nigeria
email: gazettes@codeforafrica.org
url: http://opengazettes.or.ng
jurisdiction: Nigeria
jurisdiction_adjective: Nigerian
jurisdiction_code: NG
source_attribution: "Center for Research Libraries: Global Resource Network"
source_attribution_link: https://dds.crl.edu/crldelivery/27040
enforce_ssl: opengazettes.or.ng
baseurl:
description: Making Government Gazettes freely available.
twitter:
  username: code4africa

gems:
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  gazettes:
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      image: /img/banner_5.png

# Build settings
markdown: kramdown
exclude: [vendor]

google_analytics: UA-100279361-3

aleph_url: https://opengazettes.co
s3_url: http://nigeria.opengazettes.co.s3-website-eu-west-1.amazonaws.com/

